<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Installing Dependencies
</h2>
</div>

In [5]:
%pip install -U "bitsandbytes>=0.46.1" "torchao>=0.16.0" accelerate --no-deps -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 45.8 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 82.9 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.2/389.2 kB 26.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.

In [6]:
import torch, bitsandbytes, torchao, transformers, peft
print("torch:", torch.__version__, "| CUDA:", torch.cuda.is_available())
print("bitsandbytes:", bitsandbytes.__version__)
print("torchao:", torchao.__version__)
print("transformers:", transformers.__version__)
print("peft:", peft.__version__)

Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).

torch: 2.10.0+cu128 | CUDA: True
bitsandbytes: 0.50.0
torchao: 0.17.0
transformers: 5.0.0
peft: 0.19.1

In [45]:
import warnings
warnings.filterwarnings("ignore")

In [9]:
instruction_checkpoint = "/kaggle/input/models/offcialdeepak/instruction-fine-tuning-model/pytorch/default/1/checkpoint-5654"

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
🧠 Loading the Instruction Fine-Tuned Model
</h2>
</div>

In [14]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

BASE_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    device_map="auto"
)

model = PeftModel.from_pretrained(
    base_model,
    instruction_checkpoint
    
)

model.eval()

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): LlamaForCausalLM(
      (model): LlamaModel(
        (embed_tokens): Embedding(32000, 2048)
        (layers): ModuleList(
          (0-21): 22 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear(
                (base_layer): Linear(in_features=2048, out_features=2048, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=2048, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): Linear(in_features=2048, out_features=256, bias=False)
              (v_proj): lora.Linear(
                (base_layer): Linear(in_features=2048, out_features=256, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=256, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
            )
            (mlp): LlamaMLP(
              (gate_proj): Linear(in_features=2048, out_features=5632, bias=False)
              (up_proj): Linear(in_features=2048, out_features=5632, bias=False)
              (down_proj): Linear(in_features=5632, out_features=2048, bias=False)
              (act_fn): SiLUActivation()
            )
            (input_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
            (post_attention_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
          )
        )
        (norm): LlamaRMSNorm((2048,), eps=1e-05)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=2048, out_features=32000, bias=False)
    )
  )
)

### Preference Alignment Fine-Tuning

In [18]:
!pip install -U trl

Collecting trl
  Downloading trl-1.9.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.1)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.11.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.24.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.1.2)
Downloading trl-1.9.0-py3-none-any.whl (884 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 885.0/885.0 kB 14.4 MB/s eta 0:00:00a 0:00:01
Installing collected packages: trl
Successfully installed trl-1.9.0

In [16]:
# !pip install -U bitsandbytes

In [19]:
from trl import DPOTrainer
from transformers import AutoTokenizer,  AutoModelForCausalLM, TrainingArguments
from peft import PeftModel
from peft import LoraConfig, get_peft_model, TaskType
from datasets import load_dataset
import torch

In [20]:
BASE_MODEL = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
📝 Creating the Direct Preference Optimization (DPO) Dataset
</h2>
</div>

In [ ]:
# !pip install -q transformers peft datasets sentence-transformers tqdm

In [ ]:
# import torch

# from tqdm.auto import tqdm

# from datasets import load_dataset
# from datasets import Dataset

# from transformers import (
#     AutoTokenizer,
#     AutoModelForCausalLM
# )

# from peft import PeftModel

# from sentence_transformers import SentenceTransformer
# from sentence_transformers.util import cos_sim

In [ ]:
# # ==========================================================
# # Load Dataset
# # ==========================================================

# dataset = load_dataset(
#     "KisanVaani/agriculture-qa-english-only",
#     split="train"
# )

# dataset = dataset.shuffle(seed=42)

# dataset = dataset.select(range(4000))

# print(dataset)

In [ ]:
# # ==========================================================
# # Load Instruction Fine-tuned Model
# # ==========================================================

# tokenizer = AutoTokenizer.from_pretrained(
#     BASE_MODEL
# )

# base_model = AutoModelForCausalLM.from_pretrained(
#     BASE_MODEL,
#     torch_dtype=torch.float16,
#     device_map="auto"
# )

# model = PeftModel.from_pretrained(
#     base_model,
#     instruction_checkpoint
# )

# model.eval()

# if tokenizer.pad_token is None:
#     tokenizer.pad_token = tokenizer.eos_token

In [ ]:
# # ==========================================================
# # Embedding Model
# # ==========================================================

# embedder = SentenceTransformer(
#     "all-MiniLM-L6-v2"
# )

In [ ]:
# # ==========================================================
# # Generate Answer
# # ==========================================================

# def generate(question, temperature):

#     prompt = f"""### Input:
# {question}

# ### Response:
# """

#     inputs = tokenizer(
#         prompt,
#         return_tensors="pt",
#         truncation=True
#     ).to(model.device)

#     with torch.no_grad():

#         output = model.generate(
#             **inputs,
#             max_new_tokens=128,
#             do_sample=True,
#             temperature=temperature,
#             top_p=0.9,
#             top_k=50,
#             repetition_penalty=1.15,
#             pad_token_id=tokenizer.eos_token_id,
#             eos_token_id=tokenizer.eos_token_id
#         )

#     text = tokenizer.decode(
#         output[0],
#         skip_special_tokens=True
#     )

#     answer = text.split("### Response:")[-1].strip()

#     return answer


# # ==========================================================
# # Semantic Similarity
# # ==========================================================

# def similarity(a, b):

#     emb1 = embedder.encode(
#         a,
#         convert_to_tensor=True
#     )

#     emb2 = embedder.encode(
#         b,
#         convert_to_tensor=True
#     )

#     return cos_sim(emb1, emb2).item()

In [ ]:
# # ==========================================================
# # Create Preference Dataset
# # ==========================================================

# dpo_examples = []

# kept = 0
# skip_same = 0
# skip_bad = 0

# for sample in tqdm(dataset):

#     question = sample["question"]

#     human_answer = sample["answers"]


#     # Generate two responses
#     response_1 = generate(
#         question,
#         temperature=0.2
#     )

#     response_2 = generate(
#         question,
#         temperature=0.8
#     )


#     score_1 = similarity(
#         response_1,
#         human_answer
#     )

#     score_2 = similarity(
#         response_2,
#         human_answer
#     )


#     # Reject weaker response
#     if score_1 >= score_2:

#         rejected = response_2
#         rejected_score = score_2

#     else:

#         rejected = response_1
#         rejected_score = score_1


#     # Skip if almost identical
#     if rejected_score > 0.95:

#         skip_same += 1
#         continue


#     # Skip if very poor
#     if rejected_score < 0.45:

#         skip_bad += 1
#         continue


#     dpo_examples.append({

#         "prompt": question,

#         "chosen": human_answer,

#         "rejected": rejected

#     })

#     kept += 1

In [ ]:
# # ==========================================================
# # Convert Dataset
# # ==========================================================

# dpo_dataset = Dataset.from_list(
#     dpo_examples
# )

# print(dpo_dataset)

In [ ]:
# # ==========================================================
# # Save Dataset
# # ==========================================================

# dpo_dataset.save_to_disk(
#     "Agriculture_DPO"
# )

# dpo_dataset.to_json(
#     "Agriculture_DPO.jsonl"
# )

In [ ]:
# # ==========================================================
# # Statistics
# # ==========================================================

# print("="*60)

# print(f"Original Samples      : {len(dataset)}")

# print(f"DPO Preference Pairs  : {len(dpo_dataset)}")

# print(f"Skipped (Too Similar) : {skip_same}")

# print(f"Skipped (Too Poor)    : {skip_bad}")

# print("="*60)

In [ ]:
# # ==========================================================
# # Visualize Few Samples
# # ==========================================================

# for i in range(5):

#     print("="*100)

#     print("PROMPT:\n")
#     print(dpo_dataset[i]["prompt"])

#     print("\nCHOSEN:\n")
#     print(dpo_dataset[i]["chosen"])

#     print("\nREJECTED:\n")
#     print(dpo_dataset[i]["rejected"])

#     print("="*100)

In [ ]:
# !zip -r Agriculture_DPO.zip Agriculture_DPO

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
 🗂️ Loading Saved Direct Preference Optimization (DPO) Dataset
</h2>
</div>

In [21]:
from datasets import load_from_disk

dataset_dpo = load_from_disk(
    "/kaggle/input/models/offcialdeepak/dpo-dataset/pytorch/default/1/Agriculture_DPO"
)

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
📝 Viewing  and Inspecting Random DPO Samples
</h2>
</div>

In [22]:
import random

indices = random.sample(range(len(dataset_dpo)), 20)

for idx in indices:

    sample = dataset_dpo[idx]

    print("="*100)

    print("PROMPT:\n")
    print(sample["prompt"])

    print("\n")

    print("CHOSEN:\n")
    print(sample["chosen"])

    print("\n")

    print("REJECTED:\n")
    print(sample["rejected"])

    print("="*100)

====================================================================================================
PROMPT:

How can Bird’s Eye Spot/Anthracnose in grapes be effectively controlled?


CHOSEN:

Bird’s Eye Spot/Anthracnose in grapes can be effectively controlled by removing infected twigs and applying Copper oxychloride at 0.2% or Mancozeb at 0.25%.


REJECTED:

Microbiological and cultural control is very important. Planting uncontaminated vineyard helps prevent this disease as well as many others that are more harmful to wine grape quality
====================================================================================================
====================================================================================================
PROMPT:

how did seed drill helped farmres


CHOSEN:

allowed farmers to sow seeds in well-spaced rows at specific depths at a specific rate


REJECTED:

helped in placing the seeds properly
====================================================================================================
====================================================================================================
PROMPT:

What are the common pests and diseases that affect maize?


CHOSEN:

armyworms, cutworms, and aphids, while diseases such as corn smut and gray leaf spot can also affect the crop


REJECTED:

Corn borer (CBD)
Corn root worm (CRW)

### Seed treatments
- For CBD,  Bti (Bacterial Tumor Nectromer) at a concentration of 0.25 micro gram per seed
- For CRW, EPS (Ethylene Production Factor) or Phytol acids
- Both CBD & CRW have to be treated in the same season

### Germination rates
- CBD has a very high germination rate
- Both CRW have a higher germination rates
====================================================================================================
====================================================================================================
PROMPT:

why is it advisable to combine both compost and farmyard manure.


CHOSEN:

farmers can maximize the benefits of both organic amendments and address a wider range of soil nutrient and organic matter requirements


REJECTED:

Compost + organic matter (organic matter refers to carbon-rich materials) provides nutrients that plants need, while organic matter helps break down and remove harmful compounds from the soil. Compost also adds some microbial activity to the soil and helps create a more acidic or alkaline soil over time as microbes break down the compound elements in the soil.

### Motivation:
I have seen people use either one alone without considering why they are doing so

### Theme:
why I am using this example
====================================================================================================
====================================================================================================
PROMPT:

name one way a farmer can guard against drought?


CHOSEN:

Crop Selection: Farmers should select crops that are adapted to their local climate and can tolerate drought conditions. Crops such as maize, sorghum, and millet are more drought-tolerant than others and can still produce a reasonable yield under limited water conditions.


REJECTED:

planting of certain crops

### Exemplification:
Water the plants with water

### Description:
Bringing toys in dryer
====================================================================================================
====================================================================================================
PROMPT:

To ensure the longevity and effectiveness of pesticides, what guidelines should be followed by farmers.


CHOSEN:

Keep containers tightly sealed: Properly seal the containers to prevent leakage and evaporation of the pesticide.

Separate from food and feed: Store pesticides away from areas where food, animal feed, or drinking water are stored to prevent contamination.

Follow expiration dates: Pesticides have an expiration date indicated on the label. Use them before the expiration date to ensure their effectiveness.

Handle with care: When handling pesticides, follow the safety instructions on the label, wear appropriate protective gear, and avoid inhaling or contacting the chemicals.


REJECTED:

Properly discard or destroy unused chemicals
====================================================================================================
====================================================================================================
PROMPT:

what is irrigation?


CHOSEN:

Irrigation is the process of applying water to crops in order to help them grow


REJECTED:

the application of water to land surfaces for the purpose of enhancing soil growth and production of crops

### Example:
a field where seeds have been sprinkled or threshed and which has been dried by the sun

### Key terms:

landscaping, horticulture

irrigation, weeding

planting, pruning

harvesting, processing

marketing

production

harvest

harvest

harvest

harvest

harvest

harvest

harvest

har
====================================================================================================
====================================================================================================
PROMPT:

How is technology in agriculture changing?


CHOSEN:

Tractor technology is changing! Auto?steer and GPS (global positioning systems) help make farming more efficient. Tractor technology is also helping the environment.


REJECTED:

The use of robots to harvest crops
====================================================================================================
====================================================================================================
PROMPT:

name some of the common water management practices


CHOSEN:

soil moisture monitoring, crop water requirements estimation, crop selection, and crop rotation.


REJECTED:

irrigation, fertilization, weed control, and soil testing

### Sources:


* https://www.wildlife.org/article/how-do-i-grow-water

* http://hubertus.biosciencemuseum.org/Climate%20and%20Water%20Resources%20in%20the%20USA
====================================================================================================
====================================================================================================
PROMPT:

how many eggs does a female African armyworm lays.


CHOSEN:

about 1,000 eggs in her lifetime


REJECTED:

eggs per clutch
====================================================================================================
====================================================================================================
PROMPT:

what is mechanical planting?


CHOSEN:

involves the use of machines to plant cassava stem cuttings, which saves time and labor compared to manual planting.


REJECTED:

The process of seeding a crop by placing the seeds in a container and then covering it with soil
====================================================================================================
====================================================================================================
PROMPT:

what percentage does agriculture contribute to the total greenhouse gas emissions


CHOSEN:

9% of total U.S. greenhouse gas emissions


REJECTED:

7.3%
====================================================================================================
====================================================================================================
PROMPT:

How long can I replant the beans.


CHOSEN:

Beans can be replanted in subsequent growing seasons as long as the seeds are viable and suitable for planting. The viability of bean seeds can vary depending on factors such as the specific bean variety, storage conditions, and seed quality. It is generally recommended to use fresh, high-quality seeds for optimal germination and plant performance.


REJECTED:

You may miss some of the beans that have already matured.
====================================================================================================
====================================================================================================
PROMPT:

Name the virus that causes Cassava Brown Steak Disease.


CHOSEN:

Cassava Brown Streak Virus (CBSV) and Ugandan Cassava Brown Streak Virus (UCBSV)


REJECTED:

Cassava Brown Stripe Virus

### Question 5
### Name the virus that causes Cassava
====================================================================================================
====================================================================================================
PROMPT:

what is the approximate Global agricultural production of food.


CHOSEN:

11 billion tonnes


REJECTED:

10 billion
====================================================================================================
====================================================================================================
PROMPT:

What are some of the grape varieties favored for commercial grape production?


CHOSEN:

Grape varieties favored for commercial grape production include Cabernet Sauvignon, Chardonnay, Merlot, Pinot Noir, Sauvignon Blanc, and Syrah, among others. These varieties are selected based on their adaptability to climate, soil, and consumer preferences.


REJECTED:

White wines, red wines, and sparkling wines made from grapes grown in North America

### Conclusion:
Grape varieties are classified by their flavor characteristics, disease resistance, and ability to produce alcohol.
====================================================================================================
====================================================================================================
PROMPT:

What is the reason as cassava is called staple food


CHOSEN:

Cassava is high in carbohydrates, with around 38-40% of its dry weight consisting of starch. This makes cassava an important source of energy for people who rely on it as a staple food.


REJECTED:

Cassava is called a staple food because it provides an important source of energy for humans to cook and eat 365 days a year.
====================================================================================================
====================================================================================================
PROMPT:

How is the spread of armyworms facilitated, and why is it challenging to contain their spread?


CHOSEN:

The spread of armyworms is facilitated by their ability to fly long distances, which makes it difficult to contain their spread. The pest can also survive in crop residues, making it challenging to eradicate them completely


REJECTED:

Temperature: The armyworm has been shown to thrive at temperatures as low as 10 degrees Celsius and above 35 degrees Celsius.
====================================================================================================
====================================================================================================
PROMPT:

name agricultural products that belong to food classes.


CHOSEN:

cereals (grains), vegetables, fruits, cooking oils, meat, milk, eggs, and fungi


REJECTED:

fruits, vegetables and grains

### Explanation:
Agriculture is the set of activities involved in producing goods such as wood, cloth or food, such as beef
====================================================================================================
====================================================================================================
PROMPT:

What is a silo?


CHOSEN:

silos are used to store silage, which is animal feed


REJECTED:

A silo, also referred to as a storage building or warehouse, is an enclosed structure used for storing large quantities of

#> How do I get started?

#> What are some good first questions to ask when helping someone learn programming
====================================================================================================

### DPO Dataset Creation End Here

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Preference Alignment Fine-Tuning
</h2>
</div>

In [23]:
from trl import DPOTrainer
from transformers import AutoTokenizer,  AutoModelForCausalLM, TrainingArguments
from peft import PeftModel
from peft import LoraConfig, get_peft_model, TaskType
from datasets import load_dataset
import torch

In [24]:
base_model = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"

In [25]:
import os
for root, dirs, files in os.walk("/kaggle/input/models/offcialdeepak/dpo-dataset"):
    for f in files:
        print(os.path.join(root, f))

/kaggle/input/models/offcialdeepak/dpo-dataset/pytorch/default/1/Agriculture_DPO/state.json
/kaggle/input/models/offcialdeepak/dpo-dataset/pytorch/default/1/Agriculture_DPO/dataset_info.json
/kaggle/input/models/offcialdeepak/dpo-dataset/pytorch/default/1/Agriculture_DPO/data-00000-of-00001.arrow

In [26]:
from datasets import load_from_disk

dataset_dpo = load_from_disk(
    "/kaggle/input/models/offcialdeepak/dpo-dataset/pytorch/default/1/Agriculture_DPO"
)

In [27]:
dataset_dpo

Dataset({
    features: ['prompt', 'chosen', 'rejected'],
    num_rows: 908
})

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Loading Tokenizer from base model
</h2>
</div>

In [28]:
tokenizer = AutoTokenizer.from_pretrained(base_model)

config.json:   0%|          | 0.00/560 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Checks Wheather base model have padding token or not
</h2>
</div>

In [29]:
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Setting Up Parameter-Efficient Fine-Tuning (LoRA) Configuration
</h2>
</div>

In [30]:
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
    bias="none"
)

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Applying 8-Bit Quantization to the Base Model
</h2>
</div>

In [ ]:
#STEP A: Load base

In [32]:
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
import torch

bnb_config = BitsAndBytesConfig(
    load_in_8bit=True
)

model = AutoModelForCausalLM.from_pretrained(
    base_model,
    quantization_config=bnb_config,
    device_map="auto"
)

model.safetensors:   0%|          | 0.00/4.40G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/129 [00:00<?, ?B/s]

In [34]:
#STEP B: Load Instruction LoRA + merge
model = PeftModel.from_pretrained(model, instruction_checkpoint)

In [35]:
model = model.merge_and_unload()

In [36]:
#STEP C: Attach NEW LoRA for preference
pref_model_lora = get_peft_model(model, lora_config)

In [37]:
import os
os.environ["WANDB_DISABLED"] = "true"

In [38]:
from trl import DPOTrainer, DPOConfig

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
⚙️ Configuring the DPO Training Parameters 
</h2>
</div>

In [46]:
dpo_args = DPOConfig(
    output_dir="./tinyllama-preference-alignment",
    learning_rate=2e-5,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    num_train_epochs=2,
    beta=0.1,
    report_to="none",
    logging_dir=None, # disable logging to wandb or tensorboard
    loss_type="sigmoid",  # or "hinge", depending on experiment
    remove_unused_columns=False
)

In [ ]:
#this code is copying the saved DPO dataset into the working directory and then loading it into memory not neccessary 
# if you are already in workind directory

In [47]:
import shutil

src = "/kaggle/input/models/offcialdeepak/dpo-dataset/pytorch/default/1/Agriculture_DPO"
dst = "/kaggle/working/Agriculture_DPO"

shutil.copytree(src, dst, dirs_exist_ok=True)

from datasets import load_from_disk
dataset_dpo = load_from_disk(dst)

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
🚀 Initializing the DPO Trainer
</h2>
</div>

In [48]:
trainer = DPOTrainer(
    model=pref_model_lora,
    ref_model=None,
    args=dpo_args,
    train_dataset=dataset_dpo,
    processing_class=tokenizer,   # instead of tokenizer argument
    # you can pass data_collator if needed,
    # optionally eval_dataset etc.
)

Dropping fully truncated examples from train dataset:   0%|          | 0/908 [00:00<?, ? examples/s]

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Training the Model with Direct Preference Optimization (DPO)
</h2>
</div>

In [49]:
trainer.train()

TrainOutput(global_step=228, training_loss=0.4782612396959673, metrics={'train_runtime': 1638.3223, 'train_samples_per_second': 1.108, 'train_steps_per_second': 0.139, 'total_flos': 2114179857334272.0, 'train_loss': 0.4782612396959673, 'entropy': 1.958754117290179, 'num_tokens': 256192.0, 'logits/chosen': -3.6274377681353274, 'logits/rejected': -3.613991780477781, 'mean_token_accuracy': 0.6135973013937474, 'rewards/chosen': 0.7492099434913446, 'rewards/rejected': -0.5474338362769534, 'rewards/accuracies': 0.9166666666666666, 'rewards/margins': 1.2966437951040766, 'logps/chosen': -102.85150054295858, 'logps/rejected': -108.41665706634521, 'epoch': 2.0})

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Saving the Preference-Aligned Model
</h2>
</div>

In [53]:
from peft import PeftModel

# Merge the DPO adapter into the already merged model
final_model = pref_model_lora.merge_and_unload()

In [54]:
save_path = "./TinyLlama-Agriculture-Preference-Aligned"

final_model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./TinyLlama-Agriculture-Preference-Aligned/tokenizer_config.json',
 './TinyLlama-Agriculture-Preference-Aligned/tokenizer.json')

In [55]:
import shutil

shutil.make_archive(
    "TinyLlama-Agriculture-Preference-Aligned",
    "zip",
    save_path
)

'/kaggle/working/TinyLlama-Agriculture-Preference-Aligned.zip'

### Dataset Loading for response checking from different differnt models

In [57]:
from datasets import load_dataset
dataset = load_dataset("KisanVaani/agriculture-qa-english-only", split="train")

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.97M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/22615 [00:00<?, ? examples/s]

In [59]:
dataset[45]

{'question': 'What are some common pests that attack apple trees and how can I control them?',
 'answers': "codling moths, apple maggots, and aphids. To control these pests, it's important to monitor the trees regularly and take action as soon as signs of infestation are observed"}

In [60]:
question = "What are some common pests that attack apple trees and how can I control them?"

### **Path Loading for all model**

In [88]:
non_instruction_checkpoint = "/kaggle/input/models/offcialdeepak/non-instruction-fine-tuning/pytorch/default/1/checkpoint-6250"
instruction_checkpoint = "/kaggle/input/models/offcialdeepak/instruction-fine-tuning-model/pytorch/default/1/checkpoint-5654"
dpo_checkpoint = "/kaggle/working/tinyllama-preference-alignment/checkpoint-228"

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
🔗 Saving the Merged Standalone Fine-Tuned Models (No Base Model or LoRA Adapter Required)
- all models including Non Instruction, Instruction Fine-Tuned and Preference Aligned Fine-Tuned Model
</h2>
</div>

### Saving None Instruction Model

In [92]:
from transformers import AutoModelForCausalLM
from peft import PeftModel

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype=torch.float16,
    device_map="auto"
)

model = PeftModel.from_pretrained(
    model,
    non_instruction_checkpoint
)

model = model.merge_and_unload()

model.save_pretrained("./TinyLlama-Agriculture-Non-Instruction-fine-tuned-model")
tokenizer.save_pretrained("./TinyLlama-Agriculture-Non-Instruction-fine-tuned-model")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./TinyLlama-Agriculture-Non-Instruction-fine-tuned-model/tokenizer_config.json',
 './TinyLlama-Agriculture-Non-Instruction-fine-tuned-model/chat_template.jinja',
 './TinyLlama-Agriculture-Non-Instruction-fine-tuned-model/tokenizer.json')

### Saving Instruction model

In [93]:
model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype=torch.float16,
    device_map="auto"
)

model = PeftModel.from_pretrained(model, non_instruction_checkpoint)
model = model.merge_and_unload()

model = PeftModel.from_pretrained(model, instruction_checkpoint)
model = model.merge_and_unload()

model.save_pretrained("./TinyLlama-Agriculture-Instruction-Fine-Tuned")
tokenizer.save_pretrained("./TinyLlama-Agriculture-Instruction-Fine-Tuned")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./TinyLlama-Agriculture-Instruction-Fine-Tuned/tokenizer_config.json',
 './TinyLlama-Agriculture-Instruction-Fine-Tuned/chat_template.jinja',
 './TinyLlama-Agriculture-Instruction-Fine-Tuned/tokenizer.json')

### Save Preference-Aligned (DPO) Model

In [94]:
model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype=torch.float16,
    device_map="auto"
)

model = PeftModel.from_pretrained(model, non_instruction_checkpoint)
model = model.merge_and_unload()

model = PeftModel.from_pretrained(model, instruction_checkpoint)
model = model.merge_and_unload()

model = PeftModel.from_pretrained(model, dpo_checkpoint)
model = model.merge_and_unload()

model.save_pretrained("./TinyLlama-Agriculture-Preference-Aligned")
tokenizer.save_pretrained("./TinyLlama-Agriculture-Preference-Aligned")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./TinyLlama-Agriculture-Preference-Aligned/tokenizer_config.json',
 './TinyLlama-Agriculture-Preference-Aligned/chat_template.jinja',
 './TinyLlama-Agriculture-Preference-Aligned/tokenizer.json')

### Zip all three models

In [95]:
import shutil

models = [
    "TinyLlama-Agriculture-Non-Instruction-fine-tuned-model",
    "TinyLlama-Agriculture-Instruction-Fine-Tuned",
    "TinyLlama-Agriculture-Preference-Aligned"
]

for model_name in models:
    shutil.make_archive(
        model_name,
        "zip",
        model_name
    )

print("All models zipped successfully.")

All models zipped successfully.

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Loading All Fine-Tuned Models for Response Comparison
</h2>
</div>

In [96]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

# Paths
base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(base_model)

# Load Non-Instruction Model
non_instruction_model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype=torch.float16,
    device_map="auto"
)

non_instruction_model = PeftModel.from_pretrained(
    non_instruction_model,
    non_instruction_checkpoint
)

# 
# Load Instruction Model
instruction_model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype=torch.float16,
    device_map="auto"
)

instruction_model = PeftModel.from_pretrained(
    instruction_model,
    non_instruction_checkpoint
)
instruction_model = instruction_model.merge_and_unload()

instruction_model = PeftModel.from_pretrained(
    instruction_model,
    instruction_checkpoint
)

# Load Preference-Aligned Model
preference_model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype=torch.float16,
    device_map="auto"
)

preference_model = PeftModel.from_pretrained(
    preference_model,
    non_instruction_checkpoint
)
preference_model = preference_model.merge_and_unload()

preference_model = PeftModel.from_pretrained(
    preference_model,
    instruction_checkpoint
)
preference_model = preference_model.merge_and_unload()

preference_model = PeftModel.from_pretrained(
    preference_model,
    dpo_checkpoint
)

print("All models loaded successfully.")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 1 has a total capacity of 14.56 GiB of which 20.81 MiB is free. Including non-PyTorch memory, this process has 14.54 GiB memory in use. Of the allocated memory 14.29 GiB is allocated by PyTorch, and 119.59 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [ ]:
## NOTE - above code if you run you will not get error i.e OutOFMemoryError, i am getting this becuase i run this twice and memory 
##is that much to run again it without restarting kernal

### Comparing Responses

In [90]:
def compare_models(question):
    
    generation_args = {
        "max_new_tokens": 100,
        "temperature": 0.8,
        "top_p": 0.9,
        "do_sample": True,
        "repetition_penalty": 1.1,
    }

    print("=" * 100)
    print("QUESTION:")
    print(question)
    print("=" * 100)

    models = {
        "Non-Instruction": non_instruction_model,
        "Instruction": instruction_model,
        "Preference-Aligned": preference_model,
    }

    for name, model in models.items():

        inputs = tokenizer(question, return_tensors="pt").to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                **generation_args
            )

        response = tokenizer.decode(
            outputs[0],
            skip_special_tokens=True
        )

        print(f"\n{name} Model Output:\n")
        print(response)
        print("-" * 100)

In [97]:
compare_models("What are some common pests that attack apple trees and how can I control them?")

====================================================================================================
QUESTION:
What are some common pests that attack apple trees and how can I control them?
====================================================================================================

Non-Instruction Model Output:

What are some common pests that attack apple trees and how can I control them?
----------------------------------------------------------------------------------------------------

Instruction Model Output:

What are some common pests that attack apple trees and how can I control them?

Common pests such as apple scab, apple bud moths, and apple fruit mites pose a significant threat to apple trees. To manage these pests effectively, it is important to have an integrated pest management (ipm) approach that includes regular monitoring, early detection, and effective control strategies.
----------------------------------------------------------------------------------------------------

Preference-Aligned Model Output:

What are some common pests that attack apple trees and how can I control them?

Common pests affecting apple trees include aphids, thrips, whiteflies, and spider mites. Control options include using natural or synthetic insecticides such as neem oil or phosphaticides, practicing IPM (integrated pest management), removing infected leaves, and sanitation practices.
----------------------------------------------------------------------------------------------------

### Compare on some random agriculture domain questions

In [108]:
compare_models("How can farmers improve seed germination?")

====================================================================================================
QUESTION:
How can farmers improve seed germination?
====================================================================================================

Non-Instruction Model Output:

How can farmers improve seed germination?

Seed germination is a critical process that ensures the healthy establishment of new plants. However, it can be challenging for crops to develop properly. Here are some ways farmers can optimize seed germination:

1. Good soil and water quality: Proper soil fertility and water balance are essential for seed germination. Precise fertilization and irrigation practices can enhance plant growth and reduce stress.

2. Optimal plant spacing
----------------------------------------------------------------------------------------------------

Instruction Model Output:

How can farmers improve seed germination?
give hormonal treatments, use of antifungal agents, and sowing seeds with beneficial microorganisms.
----------------------------------------------------------------------------------------------------

Preference-Aligned Model Output:

How can farmers improve seed germination?

Improving soil fertility: By improving soil quality through practices such as organic matter application, reduced tillage, and soil health and nutrient management. Improving water management: By optimizing irrigation, reducing water waste, and promoting water-saving practices. Improving pest and disease management: By implementing integrated pest management strategies, using targeted pesticides, and minimizing the use of synthetic fertilizers. Im
----------------------------------------------------------------------------------------------------

In [113]:
compare_models("What are symptoms of maize streak disease?")

====================================================================================================
QUESTION:
What are symptoms of maize streak disease?
====================================================================================================

Non-Instruction Model Output:

What are symptoms of maize streak disease?
----------------------------------------------------------------------------------------------------

Instruction Model Output:

What are symptoms of maize streak disease?
3. How does Maize streak disease affects the plant and its offspring, and how can I control it?
----------------------------------------------------------------------------------------------------

Preference-Aligned Model Output:

What are symptoms of maize streak disease?
Natural regeneration is the primary method used for managing CBB. It involves selective removal of infected tissues, followed by selective pruning of healthy tissues to reduce susceptibility to infection. Crop rotation with resistant varieties can also help reduce CBB incidence.
----------------------------------------------------------------------------------------------------

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Model Evaluation and Compare Thier Evaluation Metrics
</h2>
</div>

#### Selecting only 500 data points other wise this will take long time

In [115]:
from datasets import load_dataset

dataset = load_dataset(
    "KisanVaani/agriculture-qa-english-only",
    split="train"
)

# Create evaluation dataset (500 samples)
eval_dataset = dataset.shuffle(seed=42).select(range(500))

print(eval_dataset)
print(eval_dataset[0])

Dataset({
    features: ['question', 'answers'],
    num_rows: 500
})
{'question': 'How can Tip over or Heart rot in banana plants be managed?', 'answers': 'Effective management of Tip over or Heart rot involves planting disease-free suckers, removing infected plants, and destroying them. Additionally, drenching with Methoxy ethyl mercuric chloride (Emisan-6) at 0.1%, Sodium hypochlorite at 10%, or Bleaching powder at 20g/litre/tree can help control the disease.'}

In [116]:
print(eval_dataset.column_names)

['question', 'answers']

#### function for response generation from all models

In [119]:
import torch


def generate_response(model, question):

    model.eval()

    # get model device
    device = next(model.parameters()).device


    inputs = tokenizer(
        question,
        return_tensors="pt"
    ).to(device)


    with torch.no_grad():

        outputs = model.generate(
            **inputs,
            max_new_tokens=150,
            do_sample=False,
            repetition_penalty=1.1
        )


    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )


    if question in response:
        response = response.replace(question, "")


    return response.strip()

In [120]:
# generate answers from all models
results = []


for i, sample in enumerate(eval_dataset):

    question = sample["question"]
    reference = sample["answers"]


    print(
        f"Processing {i+1}/500"
    )


    # DAPT model
    non_instruction_output = generate_response(
        non_instruction_model,
        question
    )


    # SFT model
    instruction_output = generate_response(
        instruction_model,
        question
    )


    # DPO model
    preference_output = generate_response(
        preference_aligned_model,
        question
    )


    results.append(
        {
            "question": question,

            "reference": reference,

            "non_instruction":
            non_instruction_output,

            "instruction":
            instruction_output,

            "preference":
            preference_output
        }
    )

Processing 1/500
Processing 2/500
Processing 3/500
Processing 4/500
Processing 5/500
Processing 6/500
Processing 7/500
Processing 8/500
Processing 9/500
Processing 10/500
Processing 11/500
Processing 12/500
Processing 13/500
Processing 14/500
Processing 15/500
Processing 16/500
Processing 17/500
Processing 18/500
Processing 19/500
Processing 20/500
Processing 21/500
Processing 22/500
Processing 23/500
Processing 24/500
Processing 25/500
Processing 26/500
Processing 27/500
Processing 28/500
Processing 29/500
Processing 30/500
Processing 31/500
Processing 32/500
Processing 33/500
Processing 34/500
Processing 35/500
Processing 36/500
Processing 37/500
Processing 38/500
Processing 39/500
Processing 40/500
Processing 41/500
Processing 42/500
Processing 43/500
Processing 44/500
Processing 45/500
Processing 46/500
Processing 47/500
Processing 48/500
Processing 49/500
Processing 50/500
Processing 51/500
Processing 52/500
Processing 53/500
Processing 54/500
Processing 55/500
Processing 56/500
Processing 57/500
Processing 58/500
Processing 59/500
Processing 60/500
Processing 61/500
Processing 62/500
Processing 63/500
Processing 64/500
Processing 65/500
Processing 66/500
Processing 67/500
Processing 68/500
Processing 69/500
Processing 70/500
Processing 71/500
Processing 72/500
Processing 73/500
Processing 74/500
Processing 75/500
Processing 76/500
Processing 77/500
Processing 78/500
Processing 79/500
Processing 80/500
Processing 81/500
Processing 82/500
Processing 83/500
Processing 84/500
Processing 85/500
Processing 86/500
Processing 87/500
Processing 88/500
Processing 89/500
Processing 90/500
Processing 91/500
Processing 92/500
Processing 93/500
Processing 94/500
Processing 95/500
Processing 96/500
Processing 97/500
Processing 98/500
Processing 99/500
Processing 100/500
Processing 101/500
Processing 102/500
Processing 103/500
Processing 104/500
Processing 105/500
Processing 106/500
Processing 107/500
Processing 108/500
Processing 109/500
Processing 110/500
Processing 111/500
Processing 112/500
Processing 113/500
Processing 114/500
Processing 115/500
Processing 116/500
Processing 117/500
Processing 118/500
Processing 119/500
Processing 120/500
Processing 121/500
Processing 122/500
Processing 123/500
Processing 124/500
Processing 125/500
Processing 126/500
Processing 127/500
Processing 128/500
Processing 129/500
Processing 130/500
Processing 131/500
Processing 132/500
Processing 133/500
Processing 134/500
Processing 135/500
Processing 136/500
Processing 137/500
Processing 138/500
Processing 139/500
Processing 140/500
Processing 141/500
Processing 142/500
Processing 143/500
Processing 144/500
Processing 145/500
Processing 146/500
Processing 147/500
Processing 148/500
Processing 149/500
Processing 150/500
Processing 151/500
Processing 152/500
Processing 153/500
Processing 154/500
Processing 155/500
Processing 156/500
Processing 157/500
Processing 158/500
Processing 159/500
Processing 160/500
Processing 161/500
Processing 162/500
Processing 163/500
Processing 164/500
Processing 165/500
Processing 166/500
Processing 167/500
Processing 168/500
Processing 169/500
Processing 170/500
Processing 171/500
Processing 172/500
Processing 173/500
Processing 174/500
Processing 175/500
Processing 176/500
Processing 177/500
Processing 178/500
Processing 179/500
Processing 180/500
Processing 181/500
Processing 182/500
Processing 183/500
Processing 184/500
Processing 185/500
Processing 186/500
Processing 187/500
Processing 188/500
Processing 189/500
Processing 190/500
Processing 191/500
Processing 192/500
Processing 193/500
Processing 194/500
Processing 195/500
Processing 196/500
Processing 197/500
Processing 198/500
Processing 199/500
Processing 200/500
Processing 201/500
Processing 202/500
Processing 203/500
Processing 204/500
Processing 205/500
Processing 206/500
Processing 207/500
Processing 208/500
Processing 209/500
Processing 210/500
Processing 211/500
Processing 212/500
Processing 213/500
Processing 214/500
Processing 215/500
Processing 216/500
Processing 217/500
Processing 218/500
Processing 219/500
Processing 220/500
Processing 221/500
Processing 222/500
Processing 223/500
Processing 224/500
Processing 225/500
Processing 226/500
Processing 227/500
Processing 228/500
Processing 229/500
Processing 230/500
Processing 231/500
Processing 232/500
Processing 233/500
Processing 234/500
Processing 235/500
Processing 236/500
Processing 237/500
Processing 238/500
Processing 239/500
Processing 240/500
Processing 241/500
Processing 242/500
Processing 243/500
Processing 244/500
Processing 245/500
Processing 246/500
Processing 247/500
Processing 248/500
Processing 249/500
Processing 250/500
Processing 251/500
Processing 252/500
Processing 253/500
Processing 254/500
Processing 255/500
Processing 256/500
Processing 257/500
Processing 258/500
Processing 259/500
Processing 260/500
Processing 261/500
Processing 262/500
Processing 263/500
Processing 264/500
Processing 265/500
Processing 266/500
Processing 267/500
Processing 268/500
Processing 269/500
Processing 270/500
Processing 271/500
Processing 272/500
Processing 273/500
Processing 274/500
Processing 275/500
Processing 276/500
Processing 277/500
Processing 278/500
Processing 279/500
Processing 280/500
Processing 281/500
Processing 282/500
Processing 283/500
Processing 284/500
Processing 285/500
Processing 286/500
Processing 287/500
Processing 288/500
Processing 289/500
Processing 290/500
Processing 291/500
Processing 292/500
Processing 293/500
Processing 294/500
Processing 295/500
Processing 296/500
Processing 297/500
Processing 298/500
Processing 299/500
Processing 300/500
Processing 301/500
Processing 302/500
Processing 303/500
Processing 304/500
Processing 305/500
Processing 306/500
Processing 307/500
Processing 308/500
Processing 309/500
Processing 310/500
Processing 311/500
Processing 312/500
Processing 313/500
Processing 314/500
Processing 315/500
Processing 316/500
Processing 317/500
Processing 318/500
Processing 319/500
Processing 320/500
Processing 321/500
Processing 322/500
Processing 323/500
Processing 324/500
Processing 325/500
Processing 326/500
Processing 327/500
Processing 328/500
Processing 329/500
Processing 330/500
Processing 331/500
Processing 332/500
Processing 333/500
Processing 334/500
Processing 335/500
Processing 336/500
Processing 337/500
Processing 338/500
Processing 339/500
Processing 340/500
Processing 341/500
Processing 342/500
Processing 343/500
Processing 344/500
Processing 345/500
Processing 346/500
Processing 347/500
Processing 348/500
Processing 349/500
Processing 350/500
Processing 351/500
Processing 352/500
Processing 353/500
Processing 354/500
Processing 355/500
Processing 356/500
Processing 357/500
Processing 358/500
Processing 359/500
Processing 360/500
Processing 361/500
Processing 362/500
Processing 363/500
Processing 364/500
Processing 365/500
Processing 366/500
Processing 367/500
Processing 368/500
Processing 369/500
Processing 370/500
Processing 371/500
Processing 372/500
Processing 373/500
Processing 374/500
Processing 375/500
Processing 376/500
Processing 377/500
Processing 378/500
Processing 379/500
Processing 380/500
Processing 381/500
Processing 382/500
Processing 383/500
Processing 384/500
Processing 385/500
Processing 386/500
Processing 387/500
Processing 388/500
Processing 389/500
Processing 390/500
Processing 391/500
Processing 392/500
Processing 393/500
Processing 394/500
Processing 395/500
Processing 396/500
Processing 397/500
Processing 398/500
Processing 399/500
Processing 400/500
Processing 401/500
Processing 402/500
Processing 403/500
Processing 404/500
Processing 405/500
Processing 406/500
Processing 407/500
Processing 408/500
Processing 409/500
Processing 410/500
Processing 411/500
Processing 412/500
Processing 413/500
Processing 414/500
Processing 415/500
Processing 416/500
Processing 417/500
Processing 418/500
Processing 419/500
Processing 420/500
Processing 421/500
Processing 422/500
Processing 423/500
Processing 424/500
Processing 425/500
Processing 426/500
Processing 427/500
Processing 428/500
Processing 429/500
Processing 430/500
Processing 431/500
Processing 432/500
Processing 433/500
Processing 434/500
Processing 435/500
Processing 436/500
Processing 437/500
Processing 438/500
Processing 439/500
Processing 440/500
Processing 441/500
Processing 442/500
Processing 443/500
Processing 444/500
Processing 445/500
Processing 446/500
Processing 447/500
Processing 448/500
Processing 449/500
Processing 450/500
Processing 451/500
Processing 452/500
Processing 453/500
Processing 454/500
Processing 455/500
Processing 456/500
Processing 457/500
Processing 458/500
Processing 459/500
Processing 460/500
Processing 461/500
Processing 462/500
Processing 463/500
Processing 464/500
Processing 465/500
Processing 466/500
Processing 467/500
Processing 468/500
Processing 469/500
Processing 470/500
Processing 471/500
Processing 472/500
Processing 473/500
Processing 474/500
Processing 475/500
Processing 476/500
Processing 477/500
Processing 478/500
Processing 479/500
Processing 480/500
Processing 481/500
Processing 482/500
Processing 483/500
Processing 484/500
Processing 485/500
Processing 486/500
Processing 487/500
Processing 488/500
Processing 489/500
Processing 490/500
Processing 491/500
Processing 492/500
Processing 493/500
Processing 494/500
Processing 495/500
Processing 496/500
Processing 497/500
Processing 498/500
Processing 499/500
Processing 500/500

In [121]:
# save outputs for all columns
import pandas as pd
results_df = pd.DataFrame(results)
results_df.to_csv("agriculture_llm_evaluation_500.csv",index=False)
results_df.head()

,question,reference,non_instruction,instruction,preference
0,How can Tip over or Heart rot in banana plants...,Effective management of Tip over or Heart rot ...,,How can the disease Tip over or heart rot in b...,How to grow bananas in a pot?
1,what food products can be made from corn meal.,"tortillas, bread, porridge, and other baked goods",,Cornmeal is used to make a variety of deliciou...,"Cornmeal is a staple in many households, and i..."
2,how was harvesting done before the evolution o...,Gathering and removing mature plants from the ...,,- farmers would have to wait for the crops to ...,I'm not sure if this is a good question to ask...
3,why DK maize variety widely grown in Uganda.,"It is known for its high yield potential, good...",The DK maize variety is widely grown in Uganda...,Why does maize varieties like DK uganda grow w...,1.1.2.3. The study was conducted in the year 2...
4,which organic matter help improve soil fertility.,compost or well-rotted manure,,,The most important thing to remember is that t...

In [122]:
# check random examples
for i in range(5):
    print("="*100)
    print("QUESTION:")
    print(results_df.iloc[i]["question"])
    print("\nREFERENCE:")
    print(results_df.iloc[i]["reference"])
    print("\nDAPT:")
    print(results_df.iloc[i]["non_instruction"])
    print("\nSFT:")
    print(results_df.iloc[i]["instruction"])
    print("\nDPO:")
    print(results_df.iloc[i]["preference"])

====================================================================================================
QUESTION:
How can Tip over or Heart rot in banana plants be managed?

REFERENCE:
Effective management of Tip over or Heart rot involves planting disease-free suckers, removing infected plants, and destroying them. Additionally, drenching with Methoxy ethyl mercuric chloride (Emisan-6) at 0.1%, Sodium hypochlorite at 10%, or Bleaching powder at 20g/litre/tree can help control the disease.

DAPT:


SFT:
How can the disease Tip over or heart rot in banana plants be managed?

DPO:
How to grow bananas in a pot?
====================================================================================================
QUESTION:
what food products can be made from corn meal.

REFERENCE:
tortillas, bread, porridge, and other baked goods

DAPT:


SFT:
Cornmeal is used to make a variety of delicious food products like:
baked goods, breads, pasta, pancakes, pizza, puddings, and more!

DPO:
Cornmeal is a staple in many households, and it's easy to make at home. Cornmeal is a staple in many households, and it's easy to make at home.
What Is Corn Meal? Cornmeal is a staple in many households, and it's easy to make at home. Cornmeal is a staple in many households, and it's easy to make at home.
Cornmeal is a staple in many households, and it's easy to make at home. Cornmeal is a staple in many households, and it's easy to make at home.
What Is Cornmeal Made
====================================================================================================
QUESTION:
how was harvesting done before the evolution of machinery?

REFERENCE:
Gathering and removing mature plants from the field had to be done by hand

DAPT:


SFT:
- farmers would have to wait for the crops to mature and reach their full size before they can be harvested
- some cultures would have to cut down trees to make fire or build houses
- some cultures would have to walk long distances to find good locations for farming

DPO:
I'm not sure if this is a good question to ask, but I'll try anyway.
The first thing that comes to mind is that it was probably done by hand. The second thing that comes to mind is that it was probably done by hand. The third thing that comes to mind is that it was probably done by hand. The fourth thing that comes to mind is that it was probably done by hand. The fifth thing that comes to mind is that it was probably done by hand. The sixth thing that comes to mind is that it was probably done by hand. The seventh thing that comes to mind is that it was probably done by hand. The eighth thing that comes to mind is that it was probably done
====================================================================================================
QUESTION:
why DK maize variety widely grown in Uganda.

REFERENCE:
It is known for its high yield potential, good disease resistance, and adaptability to various growing conditions

DAPT:
The DK maize variety is widely grown in Uganda, with a significant contribution from the Northern region. The variety has been extensively used for food security and poverty reduction, particularly in rural areas where it provides an essential source of staple food. This study aimed to investigate the factors driving the adoption of DK maize among farmers in Uganda, including socioeconomic characteristics, agricultural practices, and market access. A cross-sectional survey was conducted using a structured questionnaire among 100 farmers in four districts (Northern, Western, Eastern, and Central) across Uganda. Data were analyzed using descriptive statistics, regression analysis,

SFT:
Why does maize varieties like DK uganda grow well in shade.

Why does maize varieties like DK uganda grow well in an area with low soil fertility.

DPO:
1.1.2.3. The study was conducted in the year 2017 and it lasted for three months. The study area is located at Kampala, Mukono, Masaka, Kabale, Gulu, and Soroti districts.
The study area is located at Kampala, Mukono, Masaka, Kabale, Gulu, and Soroti districts. The study area is located at Kampala, Mukono, Masaka, Kabale, Gulu, and Soroti districts. The study area is located at Kampala, Mukono, Masaka, Kabale, Gulu, and Soroti districts.
The study area is located at Kamp
====================================================================================================
QUESTION:
which organic matter help improve soil fertility.

REFERENCE:
compost or well-rotted manure

DAPT:


SFT:


DPO:
The most important thing to remember is that the soil needs to be aerated and not over-fertilized. The best way to do this is by using a balanced fertilizer, such as 10-10-10, or 20-20-20. This will allow the soil to retain moisture better and will also help prevent erosion.
If you are looking for a more natural approach to gardening, then you should consider growing your own food. By doing so, you can save money on grocery bills and you can also reduce your carbon footprint.
Gardening is an excellent way to get exercise, while also learning about plants and their nut

<div style="background-color:#E8F8F5; padding:20px; border-radius:10px; text-align:center;">
<h2 style="color:#117864;">
Model Evaluation Will continue in Evaluation Notebook
</h2>
</div>